### ISSUE TITLE
Crashes when triangulating too few points

### ISSUE THREAD

**Issue by nbogie** [mruegenberg/Delaunay#1]
Calling triangulate on too few points crashes with Exception: Prelude.head: empty list.

For example:

```
  triangulate [(Vector2 1 1)] 
```

Similarly if you happen to put in a longer list with fewer than two unique points.

For example:

```
triangulate [p,p,p,p,p]
  where p = Vector2 1 1 
```

I have a fix, including test.  I'll make a pull request.

Thanks for this library!

**Comment by mruegenberg** [comment]
I merged your fix. 

I'll pull in the tests in the next few days, as I don't have much time right now. 
I think it's probably better to put them in a separate file and tell Cabal that this is a test suite. (A la https://github.com/vincenthz/hs-siphash/blob/master/siphash.cabal)
